# Generated by Django 6.0.1 on 2026-02-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leavedocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavedocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='leavedocument',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='leavedocument',
            name='original_filename',
        ),
        migrations.AddField(
            model_name='leavedocument',
            name='file_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='leavedocument',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavedocument',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leavedocument',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
