# Generated by Django 6.0.1 on 2026-02-06 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_bankaccount_bank_bankaccount_branch_and_more'),
        ('leave', '0003_remove_leavedocument_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('total_planned_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('leave_entitlement', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('brought_forward', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION', 'Revision Requested')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revision_reason', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('employee_notes', models.TextField(blank=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_plans', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_plans',
                'ordering': ['-year', 'employee'],
                'unique_together': {('employee', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LeavePlanEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('REQUESTED', 'Leave Requested'), ('TAKEN', 'Leave Taken'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='PLANNED', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('leave_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='leave.leaveplan')),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_entry', to='leave.leaverequest')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_entries', to='leave.leavetype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_plan_entries',
                'ordering': ['leave_plan', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveReminder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('reminder_type', models.CharField(choices=[('Q4', 'Q4 Outstanding Balance'), ('PLAN_DUE', 'Leave Plan Due'), ('CF_DEADLINE', 'Carry Forward Deadline'), ('BALANCE', 'Low Balance Warning')], max_length=20)),
                ('outstanding_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_reminders', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_reminders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveCarryForwardRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_year', models.PositiveSmallIntegerField()),
                ('to_year', models.PositiveSmallIntegerField()),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('standard_carry_forward', models.DecimalField(decimal_places=2, default=5, help_text='Standard carry forward limit (default 5 days)', max_digits=5)),
                ('requested_carry_forward', models.DecimalField(decimal_places=2, max_digits=5)),
                ('additional_days_requested', models.DecimalField(decimal_places=2, help_text='Days beyond standard limit requiring CEO approval', max_digits=5)),
                ('approved_carry_forward', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('days_to_lapse', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason', models.TextField(help_text='Justification for carrying forward more than 5 days')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('HR_APPROVED', 'HR Approved'), ('CEO_APPROVED', 'CEO Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('ceo_approved_at', models.DateTimeField(blank=True, null=True)),
                ('ceo_comments', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('ceo_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceo_approved_carry_forwards', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_forward_requests', to='employees.employee')),
                ('hr_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviewed_carry_forwards', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_carry_forward_requests',
                'ordering': ['-from_year', 'employee'],
                'unique_together': {('employee', 'from_year')},
            },
        ),
    ]
