# Generated by Django 6.0.1 on 2026-02-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_add_location_based_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_emergency',
            field=models.BooleanField(default=False, help_text='Emergency leave types bypass advance notice requirements'),
        ),
    ]
