# Generated by Django 6.0.1 on 2026-02-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0002_initial'),
        ('payroll', '0008_payroll_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantype',
            name='auto_post_to_payroll',
            field=models.BooleanField(default=True, help_text='Automatically create payroll deduction on approval'),
        ),
        migrations.AddField(
            model_name='loantype',
            name='cooldown_months',
            field=models.PositiveSmallIntegerField(default=0, help_text='Months to wait after last deduction before applying again'),
        ),
        migrations.AddField(
            model_name='loantype',
            name='deduction_pay_component',
            field=models.ForeignKey(blank=True, help_text='Payroll component for loan deduction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_types', to='payroll.paycomponent'),
        ),
        migrations.AddField(
            model_name='loantype',
            name='salary_component',
            field=models.CharField(choices=[('GROSS', 'Gross Salary'), ('BASIC', 'Basic Salary'), ('NET', 'Net Salary')], default='GROSS', help_text='Salary component to use for calculating max amount', max_length=10),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='max_salary_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum loan amount as multiple of salary component', max_digits=4, null=True),
        ),
    ]
