# Generated by Django 6.0.1 on 2026-02-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0006_benefitclaim_tenant_benefiteligibilityrecord_tenant_and_more'),
        ('organization', '0006_alter_costcenter_code_alter_department_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefittype',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='custombenefittype',
            name='code',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='medicallensbenefit',
            name='code',
            field=models.CharField(db_index=True, default='MED_LENS', max_length=20),
        ),
        migrations.AlterField(
            model_name='professionalsubscriptiontype',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='thirdpartylender',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='benefittype',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='custombenefittype',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='expensetype',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='loantype',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='medicallensbenefit',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='professionalsubscriptiontype',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='thirdpartylender',
            unique_together={('tenant', 'code')},
        ),
    ]
