# Generated by Django 6.0.1 on 2026-02-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='cover_letter_file',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='resume_file',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='offer_letter_file',
        ),
        migrations.AddField(
            model_name='applicant',
            name='cover_letter_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='cover_letter_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='cover_letter_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='cover_letter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='cover_letter_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='offer_letter_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='offer_letter_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='offer_letter_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='offer_letter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='offer_letter_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
