# Generated by Django 6.0.1 on 2026-02-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_add_shortlisting_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='auto_shortlist',
            field=models.BooleanField(default=True, help_text='Automatically shortlist applicants who meet the defined criteria'),
        ),
    ]
