# Generated by Django 6.0.1 on 2026-02-11 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_add_auto_shortlist_to_vacancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='previous_employer_email',
            field=models.EmailField(blank=True, help_text='Email contact of previous employer', max_length=254),
        ),
        migrations.AddField(
            model_name='applicant',
            name='previous_employer_phone',
            field=models.CharField(blank=True, help_text='Phone contact of previous employer', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ACCEPTANCE_LETTER', 'Acceptance Letter'), ('PERSONAL_HISTORY', 'Personal History Form'), ('POLICE_REPORT', 'Police Report'), ('MEDICAL_REPORT', 'Medical Report'), ('BANK_DETAILS', 'Bank Details Form'), ('PROVIDENT_FUND', 'Provident Fund Form'), ('TIER_2_FORM', 'Tier 2 Form'), ('OTHER', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('file_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recruitment.applicant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applicant_documents', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applicant_documents',
                'ordering': ['document_type'],
                'unique_together': {('applicant', 'document_type')},
            },
        ),
    ]
