# Generated by Django 6.0.1 on 2026-02-11 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_processing_period_tracking'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTrainingReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_learnings', models.TextField()),
                ('skills_acquired', models.TextField()),
                ('knowledge_application', models.TextField(help_text='How the knowledge will be applied to the job')),
                ('action_plan', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('overall_rating', models.PositiveIntegerField(help_text='Overall training rating (1-5)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_training_report', to='training.trainingenrollment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingImpactAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_date', models.DateField()),
                ('assessment_period_start', models.DateField()),
                ('assessment_period_end', models.DateField()),
                ('performance_before', models.TextField()),
                ('performance_after', models.TextField()),
                ('skills_application', models.TextField()),
                ('skills_application_rating', models.PositiveIntegerField(help_text='Rating of skills application (1-5)')),
                ('impact_rating', models.CharField(choices=[('SIGNIFICANT', 'Significant Improvement'), ('MODERATE', 'Moderate Improvement'), ('MINIMAL', 'Minimal Improvement'), ('NO_CHANGE', 'No Change'), ('DECLINED', 'Performance Declined')], max_length=20)),
                ('recommendations', models.TextField(blank=True)),
                ('follow_up_actions', models.TextField(blank=True)),
                ('further_training_needed', models.BooleanField(default=False)),
                ('further_training_details', models.TextField(blank=True)),
                ('overall_effectiveness_score', models.PositiveIntegerField(help_text='Overall effectiveness score (1-5)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_impact_assessments', to='employees.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_assessment', to='training.trainingenrollment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
