# Generated by Django 6.0.1 on 2026-02-12 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_costcenter_tenant_department_tenant_and_more'),
        ('training', '0002_posttrainingreport_trainingimpactassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttrainingreport',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='trainingimpactassessment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
    ]
