# Generated by Django 6.0.1 on 2026-02-04 13:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_type', models.CharField(choices=[('SIGNUP', 'Employee Signup'), ('EMAIL_CHANGE', 'Email Change'), ('PASSWORD_RESET', 'Password Reset')], default='SIGNUP', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to='employees.employee')),
            ],
            options={
                'db_table': 'email_verification_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'token_type'], name='email_verif_email_eb6413_idx'), models.Index(fields=['token', 'is_used'], name='email_verif_token_2cb1d5_idx')],
            },
        ),
    ]
