# Generated by Django 6.0.1 on 2026-02-06 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_profile_photo_user_profile_photo_data_and_more'),
        ('core', '0003_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='district',
            field=models.ForeignKey(blank=True, help_text='Optional district scope for location-based roles', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='core.district'),
        ),
    ]
