# Generated by Django 6.0.1 on 2026-02-06 21:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_district_to_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_source',
            field=models.CharField(choices=[('LOCAL', 'Local (Email/Password)'), ('LDAP', 'LDAP/Active Directory'), ('AZURE_AD', 'Azure Active Directory')], db_index=True, default='LOCAL', help_text='The authentication provider used for this user', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='can_change_password',
            field=models.BooleanField(default=True, help_text='False for LDAP/Azure AD users'),
        ),
        migrations.AddField(
            model_name='user',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='External ID from LDAP/Azure AD', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_external_auth',
            field=models.BooleanField(default=False, help_text='User authenticates via external provider'),
        ),
        migrations.AlterField(
            model_name='authenticationlog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('2FA_SUCCESS', '2FA Success'), ('2FA_FAILED', '2FA Failed'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('LDAP_SUCCESS', 'LDAP Login Success'), ('LDAP_FAILED', 'LDAP Login Failed'), ('LDAP_SYNC', 'LDAP User Sync'), ('AZURE_SUCCESS', 'Azure AD Login Success'), ('AZURE_FAILED', 'Azure AD Login Failed'), ('PROVISIONED', 'Account Auto-Provisioned'), ('LINKED', 'Account Linked to Provider'), ('PROVIDER_CFG', 'Provider Configured')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='AuthProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('LOCAL', 'Local (Email/Password)'), ('LDAP', 'LDAP/Active Directory'), ('AZURE_AD', 'Azure Active Directory')], max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('auto_provision_users', models.BooleanField(default=True, help_text='Automatically create user accounts on first login')),
                ('auto_link_by_email', models.BooleanField(default=True, help_text='Link to existing user accounts by email')),
                ('allowed_domains', models.JSONField(blank=True, default=list, help_text='List of allowed email domains (empty = all allowed)')),
                ('last_connection_test', models.DateTimeField(blank=True, null=True)),
                ('last_connection_status', models.BooleanField(blank=True, null=True)),
                ('last_connection_error', models.TextField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_count', models.PositiveIntegerField(blank=True, null=True)),
                ('default_role', models.ForeignKey(blank=True, help_text='Default role for auto-provisioned users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_provider_defaults', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Authentication Provider',
                'verbose_name_plural': 'Authentication Providers',
                'db_table': 'auth_providers',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='authenticationlog',
            name='auth_provider',
            field=models.ForeignKey(blank=True, help_text='Authentication provider used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to='accounts.authprovider'),
        ),
        migrations.CreateModel(
            name='UserAuthProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, help_text='Unique ID from external provider (e.g., objectGUID, Azure oid)', max_length=255, null=True)),
                ('external_username', models.CharField(blank=True, help_text='Username in external system (e.g., sAMAccountName)', max_length=255, null=True)),
                ('provider_data', models.JSONField(blank=True, default=dict, help_text='Additional data from the provider')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary authentication method for this user')),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='accounts.authprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Auth Provider Link',
                'verbose_name_plural': 'User Auth Provider Links',
                'db_table': 'user_auth_providers',
                'ordering': ['-is_primary', '-last_login'],
                'indexes': [models.Index(fields=['external_id', 'provider'], name='user_auth_p_externa_164bd8_idx'), models.Index(fields=['external_username', 'provider'], name='user_auth_p_externa_4b3fa9_idx')],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
