# Generated by Django 6.0.1 on 2026-02-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_auth_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(choices=[('TOTP', 'Authenticator App'), ('EMAIL', 'Email OTP'), ('SMS', 'SMS OTP')], default='EMAIL', max_length=5),
        ),
    ]
