# Generated by Django 6.0.1 on 2026-02-12 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_two_factor_method'),
        ('organization', '0005_organization_costcenter_tenant_department_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organization.organization'),
        ),
    ]
