# Generated by Django 6.0.1 on 2026-02-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='modules',
            field=models.JSONField(blank=True, default=list, help_text='List of module codes this role grants sidebar access to.'),
        ),
    ]
