# Generated by Django 6.0.1 on 2026-02-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinaryappeal',
            name='supporting_documents',
        ),
        migrations.RemoveField(
            model_name='disciplinaryevidence',
            name='file',
        ),
        migrations.RemoveField(
            model_name='grievanceattachment',
            name='file',
        ),
        migrations.AddField(
            model_name='disciplinaryappeal',
            name='document_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='disciplinaryappeal',
            name='document_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinaryappeal',
            name='document_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disciplinaryappeal',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disciplinaryappeal',
            name='document_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinaryevidence',
            name='file_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='disciplinaryevidence',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinaryevidence',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disciplinaryevidence',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinaryevidence',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grievanceattachment',
            name='file_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='grievanceattachment',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievanceattachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grievanceattachment',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievanceattachment',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
