# Generated by Django 6.0.1 on 2026-02-08 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0002_remove_disciplinaryappeal_supporting_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinarycase',
            name='source_grievance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_cases', to='discipline.grievance'),
        ),
    ]
