# Generated by Django 6.0.1 on 2026-02-12 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0003_disciplinarycase_source_grievance'),
        ('organization', '0005_organization_costcenter_tenant_department_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaryaction',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='disciplinaryappeal',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='disciplinarycase',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='disciplinaryevidence',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='disciplinaryhearing',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='grievanceattachment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='grievancecategory',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='grievancenote',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='hearingcommitteemember',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='misconductcategory',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
    ]
