# Generated by Django 6.0.1 on 2026-02-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Full policy content (supports markdown)'),
        ),
    ]
