# Generated by Django 6.0.1 on 2026-02-04 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='original_filename',
        ),
        migrations.AddField(
            model_name='attachment',
            name='content_type_name',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(choices=[('DOCUMENT', 'Document'), ('IMAGE', 'Image'), ('CERTIFICATE', 'Certificate'), ('CONTRACT', 'Contract'), ('ID_CARD', 'ID Card'), ('MEDICAL', 'Medical Document'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('OTHER', 'Other')], default='DOCUMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['content_type_name', 'object_id'], name='attachments_content_d65242_idx'),
        ),
    ]
