# Generated by Django 6.0.1 on 2026-02-12 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_performance_indexes'),
        ('organization', '0005_organization_costcenter_tenant_department_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='announcementattachment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='announcementread',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='announcementtarget',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='district',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='region',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('schedule_config', models.JSONField(default=dict)),
                ('backup_type', models.CharField(choices=[('FULL', 'Full'), ('SELECTIVE', 'Selective'), ('INCREMENTAL', 'Incremental')], default='FULL', max_length=20)),
                ('modules_included', models.JSONField(default=list)),
                ('retention_days', models.PositiveIntegerField(default=90)),
                ('max_backups', models.PositiveIntegerField(default=30)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20, null=True)),
                ('consecutive_failures', models.SmallIntegerField(default=0)),
                ('notify_on_completion', models.BooleanField(default=False)),
                ('notify_on_failure', models.BooleanField(default=True)),
                ('notification_emails', models.JSONField(default=list)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedules', to='organization.organization')),
            ],
            options={
                'db_table': 'backup_schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantBackup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('backup_type', models.CharField(choices=[('FULL', 'Full'), ('SELECTIVE', 'Selective'), ('INCREMENTAL', 'Incremental')], default='FULL', max_length=20)),
                ('modules_included', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('RESTORING', 'Restoring')], default='PENDING', max_length=20)),
                ('progress_percent', models.SmallIntegerField(default=0)),
                ('progress_detail', models.CharField(blank=True, max_length=255)),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_checksum', models.CharField(blank=True, max_length=64)),
                ('file_format', models.CharField(default='json.gz', max_length=20)),
                ('record_counts', models.JSONField(default=dict)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('tables_included', models.JSONField(default=list)),
                ('django_version', models.CharField(blank=True, max_length=20)),
                ('schema_version', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retention_days', models.PositiveIntegerField(default=90)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='organization.organization')),
            ],
            options={
                'db_table': 'tenant_backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantRestore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restore_number', models.CharField(max_length=100, unique=True)),
                ('restore_type', models.CharField(choices=[('FULL', 'Full'), ('SELECTIVE', 'Selective'), ('MERGE', 'Merge'), ('REPLACE', 'Replace')], default='FULL', max_length=20)),
                ('modules_restored', models.JSONField(default=list)),
                ('restore_mode', models.CharField(choices=[('OVERWRITE', 'Overwrite'), ('SKIP_EXISTING', 'Skip Existing'), ('MERGE', 'Merge')], default='OVERWRITE', max_length=20)),
                ('pre_restore_completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PRE_BACKUP', 'Creating Safety Backup'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back')], default='PENDING', max_length=20)),
                ('progress_percent', models.SmallIntegerField(default=0)),
                ('progress_detail', models.CharField(blank=True, max_length=255)),
                ('records_restored', models.JSONField(default=dict)),
                ('records_skipped', models.JSONField(default=dict)),
                ('records_failed', models.JSONField(default=dict)),
                ('total_restored', models.PositiveIntegerField(default=0)),
                ('total_skipped', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_restores', to=settings.AUTH_USER_MODEL)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restores', to='core.tenantbackup')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_restores', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restores', to='organization.organization')),
                ('pre_restore_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_for_restores', to='core.tenantbackup')),
            ],
            options={
                'db_table': 'tenant_restores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenantbackup',
            index=models.Index(fields=['organization', '-created_at'], name='tenant_back_organiz_7c2a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantbackup',
            index=models.Index(fields=['status'], name='tenant_back_status_b81015_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantbackup',
            index=models.Index(fields=['expires_at'], name='tenant_back_expires_0622b2_idx'),
        ),
    ]
