# Generated by Django 5.2.1 on 2026-02-16 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_announcement_tenant_announcementattachment_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_emails_enabled', models.BooleanField(default=True)),
                ('leave_notifications', models.BooleanField(default=True)),
                ('workflow_notifications', models.BooleanField(default=True)),
                ('payroll_notifications', models.BooleanField(default=True)),
                ('performance_notifications', models.BooleanField(default=True)),
                ('recruitment_notifications', models.BooleanField(default=True)),
                ('discipline_notifications', models.BooleanField(default=True)),
                ('finance_notifications', models.BooleanField(default=True)),
                ('procurement_notifications', models.BooleanField(default=True)),
                ('training_notifications', models.BooleanField(default=True)),
                ('benefits_notifications', models.BooleanField(default=True)),
                ('employee_notifications', models.BooleanField(default=True)),
                ('exits_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Preference',
                'verbose_name_plural': 'Email Preferences',
                'db_table': 'email_preferences',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('template_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], db_index=True, default='QUEUED', max_length=20)),
                ('status_detail', models.TextField(blank=True)),
                ('sendgrid_message_id', models.CharField(blank=True, max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_email', '-created_at'], name='email_logs_recipie_d24bb8_idx'), models.Index(fields=['event_type', '-created_at'], name='email_logs_event_t_39dd8a_idx'), models.Index(fields=['status', '-created_at'], name='email_logs_status_012124_idx'), models.Index(fields=['sendgrid_message_id'], name='idx_email_log_sg_msg_id')],
            },
        ),
    ]
