# Generated by Django 6.0.1 on 2026-02-12 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, help_text='Optional period-level budget (if null, budget is for full year)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='projects.project'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='GHS', max_length=3),
        ),
        migrations.AlterField(
            model_name='organizationbankaccount',
            name='currency',
            field=models.CharField(default='GHS', max_length=3),
        ),
    ]
