# Generated by Django 6.0.1 on 2026-02-08 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvallevel',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this approval level for admin clarity'),
        ),
        migrations.AlterField(
            model_name='approvallevel',
            name='approver_type',
            field=models.CharField(choices=[('ROLE', 'By Role'), ('USER', 'Specific User'), ('SUPERVISOR', 'Direct Supervisor'), ('DEPARTMENT_HEAD', 'Department Head'), ('DISTRICT_HEAD', 'District Head'), ('REGIONAL_DIRECTOR', 'Regional Director'), ('DIRECTORATE_HEAD', 'Directorate Head'), ('DIVISION_HEAD', 'Division Head'), ('DCE', 'Deputy Chief Executive'), ('CEO', 'Chief Executive Officer'), ('DYNAMIC', 'Dynamic (Field-based)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='approvallevel',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_levels', to='workflow.workflowstate'),
        ),
    ]
