# Generated by Django 6.0.1 on 2026-02-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_costcenter_code_alter_department_code_and_more'),
        ('workflow', '0003_approvaldelegation_tenant_approvallevel_tenant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowdefinition',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='workflowdefinition',
            unique_together={('tenant', 'code', 'version')},
        ),
    ]
