# Generated by Django 6.0.1 on 2026-02-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developmentactivity',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='goalupdate',
            name='attachments',
        ),
        migrations.AddField(
            model_name='developmentactivity',
            name='evidence_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='developmentactivity',
            name='evidence_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developmentactivity',
            name='evidence_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='developmentactivity',
            name='evidence_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='developmentactivity',
            name='evidence_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalupdate',
            name='file_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='goalupdate',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalupdate',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goalupdate',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalupdate',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
