# Generated by Django 6.0.1 on 2026-02-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_costcenter_code_alter_department_code_and_more'),
        ('performance', '0006_appraisal_tenant_appraisalcycle_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='competency',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='corevalue',
            unique_together={('tenant', 'code')},
        ),
    ]
