# Generated by Django 6.0.1 on 2026-02-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.AddField(
            model_name='employee',
            name='photo_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
