# Generated by Django 6.0.1 on 2026-02-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_photo_employee_photo_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['-is_primary', 'bank__name', 'bank_name']},
        ),
    ]
