# Generated by Django 6.0.1 on 2026-02-04 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_bankaccount_options'),
        ('organization', '0002_directorate_department_directorate_division_and_more'),
        ('payroll', '0006_bank_salaryband_salarylevel_staffcategory_bankbranch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_accounts', to='payroll.bank'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_accounts', to='payroll.bankbranch'),
        ),
        migrations.AddField(
            model_name='employee',
            name='assignment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active Assignment'), ('SUSPENDED', 'Suspended Assignment'), ('ENDED', 'Ended Assignment'), ('PENDING', 'Pending Assignment')], default='ACTIVE', help_text='Current assignment status', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.directorate'),
        ),
        migrations.AddField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.division'),
        ),
        migrations.AddField(
            model_name='employee',
            name='old_staff_number',
            field=models.CharField(blank=True, db_index=True, help_text='Previous staff number from legacy system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_notch',
            field=models.ForeignKey(blank=True, help_text='Current salary notch (Band/Level/Notch)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='payroll.salarynotch'),
        ),
        migrations.AddField(
            model_name='employee',
            name='staff_category',
            field=models.ForeignKey(blank=True, help_text='Staff category for payroll grouping (e.g., District, HQ)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='payroll.staffcategory'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
