# Generated by Django 6.0.1 on 2026-02-06 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_bankaccount_bank_bankaccount_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpdateRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('request_type', models.CharField(choices=[('BANK', 'Bank Details'), ('NAME', 'Name Change'), ('ADDRESS', 'Address Update'), ('CONTACT', 'Contact Information'), ('EMERGENCY', 'Emergency Contact'), ('DEPENDENT', 'Dependent Information'), ('PERSONAL', 'Personal Information'), ('EDUCATION', 'Education/Qualifications')], db_index=True, max_length=20)),
                ('old_values', models.JSONField(default=dict, help_text='Current values before change')),
                ('new_values', models.JSONField(default=dict, help_text='Requested new values')),
                ('reason', models.TextField(help_text='Reason for the data update request')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_data_updates', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_update_requests', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_data_updates', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_data_update_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataUpdateDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('document_type', models.CharField(choices=[('MARRIAGE', 'Marriage Certificate'), ('DIVORCE', 'Divorce Certificate'), ('DEED_POLL', 'Deed Poll / Name Change'), ('BANK_CONFIRM', 'Bank Account Confirmation'), ('UTILITY', 'Utility Bill'), ('ID', 'ID Document'), ('BIRTH', 'Birth Certificate'), ('EDU_CERT', 'Educational Certificate'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_data_documents', to=settings.AUTH_USER_MODEL)),
                ('data_update_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.dataupdaterequest')),
            ],
            options={
                'db_table': 'employee_data_update_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
