# Generated by Django 6.0.1 on 2026-02-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_allow_null_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupdatedocument',
            name='file_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
