# Generated by Django 6.0.1 on 2026-02-08 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_add_file_checksum_to_data_update_document'),
        ('payroll', '0014_processing_period_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenthistory',
            name='processing_period',
            field=models.ForeignKey(blank=True, help_text='The active payroll period when this history record was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_changes_during', to='payroll.payrollperiod'),
        ),
    ]
