# Generated by Django 6.0.1 on 2026-02-12 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_bankaccount_tenant_certification_tenant_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='budget_holder',
            field=models.BooleanField(default=False, help_text='Can approve procurement spending within spending_limit'),
        ),
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Primary project assignment for cost allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employees', to='projects.project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='spending_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum procurement amount this employee can approve (GHS)', max_digits=15, null=True),
        ),
    ]
