# Generated by Django 6.0.1 on 2026-02-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_erp_schema_enhancements'),
        ('organization', '0006_alter_costcenter_code_alter_department_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequesttype',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='servicerequesttype',
            unique_together={('tenant', 'code')},
        ),
    ]
