# Generated by Django 6.0.1 on 2026-02-13 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('prompt_text', models.TextField()),
                ('category', models.CharField(choices=[('DATA_ANALYSIS', 'Data Analysis'), ('DATA_LOADING', 'Data Loading'), ('VARIATION_CHECK', 'Variation Check'), ('IMAGE_RECOGNITION', 'Image Recognition'), ('DATA_EXTRACTION', 'Data Extraction'), ('GENERAL', 'General')], max_length=20)),
                ('icon', models.CharField(default='SparklesIcon', max_length=50)),
                ('requires_file', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'assistant_prompt_templates',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_data', models.BinaryField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[('DATA', 'Data'), ('IMAGE', 'Image'), ('DOCUMENT', 'Document')], max_length=10)),
                ('parsed_summary', models.TextField(blank=True, default='')),
                ('parsed_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assistant.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='assistant.message')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_attachments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='assistant_a_convers_c8dc7b_idx'), models.Index(fields=['uploaded_by'], name='assistant_a_uploade_0a237b_idx')],
            },
        ),
    ]
