# Generated by Django 6.0.1 on 2026-02-13 08:31

import uuid
from django.db import migrations


TEMPLATES = [
    {
        'name': 'Data Analysis',
        'description': 'Analyze data files — summarize columns, data types, missing values, and key statistics',
        'prompt_text': 'Analyze this data file — summarize columns, data types, missing values, and key statistics. Highlight any notable patterns or potential data quality issues.',
        'category': 'DATA_ANALYSIS',
        'icon': 'ChartBarIcon',
        'requires_file': True,
        'sort_order': 1,
    },
    {
        'name': 'Data Loading Guide',
        'description': 'Guide for importing files into the HRMS with column mapping and issue flagging',
        'prompt_text': 'Guide me through importing this file into the HRMS. Identify the target module, map columns to the expected fields, and flag any issues or mismatches.',
        'category': 'DATA_LOADING',
        'icon': 'ArrowUpTrayIcon',
        'requires_file': True,
        'sort_order': 2,
    },
    {
        'name': 'Variation Check',
        'description': 'Compare data against expected patterns and identify anomalies or outliers',
        'prompt_text': 'Compare the data in this file against expected patterns. Identify anomalies, outliers, duplicates, and inconsistencies. Provide a summary of findings.',
        'category': 'VARIATION_CHECK',
        'icon': 'MagnifyingGlassIcon',
        'requires_file': True,
        'sort_order': 3,
    },
    {
        'name': 'Image Recognition',
        'description': 'Analyze images and extract visible text, numbers, or structured data',
        'prompt_text': 'Analyze this image and describe what you see. Extract any text, numbers, or structured data visible in the image.',
        'category': 'IMAGE_RECOGNITION',
        'icon': 'EyeIcon',
        'requires_file': True,
        'sort_order': 4,
    },
    {
        'name': 'Data Extraction',
        'description': 'Extract structured data from documents — tables, key-value pairs, and organized formats',
        'prompt_text': 'Extract structured data from this document. Identify tables, key-value pairs, and organize the information into a clean, structured format.',
        'category': 'DATA_EXTRACTION',
        'icon': 'TableCellsIcon',
        'requires_file': True,
        'sort_order': 5,
    },
    {
        'name': 'Payroll Variance',
        'description': 'Review payroll data for variances, unusual amounts, and reconciliation issues',
        'prompt_text': 'Review this payroll data for variances. Check for unusual amounts, missing deductions, duplicate entries, and reconciliation issues. Summarize findings.',
        'category': 'DATA_ANALYSIS',
        'icon': 'BanknotesIcon',
        'requires_file': True,
        'sort_order': 6,
    },
]


def seed_templates(apps, schema_editor):
    PromptTemplate = apps.get_model('assistant', 'PromptTemplate')
    for tmpl in TEMPLATES:
        PromptTemplate.objects.create(id=uuid.uuid4(), is_active=True, **tmpl)


def remove_templates(apps, schema_editor):
    PromptTemplate = apps.get_model('assistant', 'PromptTemplate')
    PromptTemplate.objects.filter(name__in=[t['name'] for t in TEMPLATES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_prompttemplate_messageattachment'),
    ]

    operations = [
        migrations.RunPython(seed_templates, remove_templates),
    ]
