# Generated by Django 5.2.1 on 2026-02-15 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_add_payroll_check_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('EMPLOYEE_TRANSACTION', 'Employee Transaction'), ('EMPLOYEE', 'Employee'), ('BANK_ACCOUNT', 'Bank Account'), ('PAY_COMPONENT', 'Pay Component'), ('BANK', 'Bank')], max_length=30)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('MAPPING', 'AI Mapping'), ('MAPPED', 'Mapped'), ('PREVIEWED', 'Previewed'), ('CONFIRMED', 'Confirmed'), ('EXECUTING', 'Executing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('column_mapping', models.JSONField(blank=True, help_text='AI-proposed column mapping: {source_col: target_field}', null=True)),
                ('confirmed_mapping', models.JSONField(blank=True, help_text='User-adjusted column mapping', null=True)),
                ('import_params', models.JSONField(blank=True, help_text='Parameters: effective_from, status, rollback_on_error, etc.', null=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('rows_errored', models.PositiveIntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('progress_key', models.CharField(blank=True, help_text='Redis cache key for live progress', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sessions', to='assistant.messageattachment')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sessions', to='assistant.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_import_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('action_taken', models.CharField(max_length=10)),
                ('record_id', models.UUIDField(blank=True, null=True)),
                ('record_type', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assistant.importsession')),
            ],
            options={
                'db_table': 'assistant_import_results',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='ImportPreviewRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('SKIP', 'Skip'), ('ERROR', 'Error')], max_length=10)),
                ('parsed_data', models.JSONField(help_text='Mapped data after column mapping')),
                ('raw_data', models.JSONField(help_text='Original row from the file')),
                ('existing_record_id', models.UUIDField(blank=True, help_text='PK of existing record for UPDATE actions', null=True)),
                ('changes', models.JSONField(blank=True, help_text='Diff: {field: {old: ..., new: ...}} for UPDATE actions', null=True)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('warnings', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_rows', to='assistant.importsession')),
            ],
            options={
                'db_table': 'assistant_import_preview_rows',
                'ordering': ['row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='importsession',
            index=models.Index(fields=['user', '-created_at'], name='assistant_i_user_id_0536d9_idx'),
        ),
        migrations.AddIndex(
            model_name='importsession',
            index=models.Index(fields=['status'], name='assistant_i_status_cae6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='importpreviewrow',
            index=models.Index(fields=['session', 'action'], name='assistant_i_session_286964_idx'),
        ),
    ]
