# Generated by Django 6.0.1 on 2026-02-04 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paycomponent',
            name='approval_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paycomponent',
            name='category',
            field=models.CharField(choices=[('BASIC', 'Basic Salary'), ('ALLOWANCE', 'Allowance'), ('BONUS', 'Bonus'), ('STATUTORY', 'Statutory Deduction'), ('OVERTIME', 'Overtime'), ('SHIFT', 'Shift Allowance'), ('LOAN', 'Loan Deduction'), ('FUND', 'Fund Contribution'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='paycomponent',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmployeeTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('override_type', models.CharField(choices=[('NONE', 'Use Default'), ('FIXED', 'Fixed Amount'), ('PCT', 'Custom Percentage'), ('FORMULA', 'Custom Formula')], default='NONE', max_length=20)),
                ('override_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('override_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('override_formula', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='transaction_documents/%Y/%m/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='employees.employee')),
                ('pay_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_transactions', to='payroll.paycomponent')),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_transactions', to='payroll.payrollperiod')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='employee_tr_employe_6c2a87_idx'), models.Index(fields=['pay_component', 'status'], name='employee_tr_pay_com_186533_idx'), models.Index(fields=['effective_from', 'effective_to'], name='employee_tr_effecti_19312a_idx')],
            },
        ),
    ]
