# Generated by Django 6.0.1 on 2026-02-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_add_employee_transaction_and_component_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycomponent',
            name='is_bonus',
            field=models.BooleanField(default=False, help_text='If True, this earning is treated as bonus and taxed at special rates'),
        ),
        migrations.AddField(
            model_name='paycomponent',
            name='is_overtime',
            field=models.BooleanField(default=False, help_text='If True, this earning is treated as overtime and taxed at special rates'),
        ),
        migrations.AddField(
            model_name='paycomponent',
            name='reduces_taxable',
            field=models.BooleanField(default=False, help_text='For deductions: if True, this deduction reduces taxable income (pre-tax deduction)'),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='bonus_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='overtime_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='total_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='total_overtime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_bonus_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_overtime_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
