# Generated by Django 6.0.1 on 2026-02-04 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_add_overtime_bonus_tax_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeBonusTaxConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Ghana Tax Configuration', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('overtime_annual_salary_threshold', models.DecimalField(decimal_places=2, default=18000, help_text='Annual salary threshold for overtime tax eligibility (GHS). Employees earning above this have overtime taxed via PAYE.', max_digits=12)),
                ('overtime_basic_percentage_threshold', models.DecimalField(decimal_places=2, default=50, help_text='Percentage of monthly basic salary threshold for lower overtime tax rate', max_digits=5)),
                ('overtime_rate_below_threshold', models.DecimalField(decimal_places=2, default=5, help_text='Tax rate (%) for overtime up to the basic percentage threshold', max_digits=5)),
                ('overtime_rate_above_threshold', models.DecimalField(decimal_places=2, default=10, help_text='Tax rate (%) for overtime exceeding the basic percentage threshold', max_digits=5)),
                ('bonus_annual_basic_percentage_threshold', models.DecimalField(decimal_places=2, default=15, help_text='Percentage of annual basic salary threshold for flat bonus tax rate', max_digits=5)),
                ('bonus_flat_rate', models.DecimalField(decimal_places=2, default=5, help_text='Flat tax rate (%) for bonus up to the threshold', max_digits=5)),
                ('bonus_excess_to_paye', models.BooleanField(default=True, help_text='If True, bonus exceeding threshold is added to taxable income for PAYE')),
                ('non_resident_overtime_rate', models.DecimalField(decimal_places=2, default=20, help_text='Flat overtime tax rate (%) for non-residents', max_digits=5)),
                ('non_resident_bonus_rate', models.DecimalField(decimal_places=2, default=20, help_text='Flat bonus tax rate (%) for non-residents', max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overtime & Bonus Tax Configuration',
                'verbose_name_plural': 'Overtime & Bonus Tax Configurations',
                'db_table': 'overtime_bonus_tax_config',
                'ordering': ['-effective_from'],
            },
        ),
    ]
