# Generated by Django 6.0.1 on 2026-02-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_add_overtime_bonus_tax_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='employeetransaction',
            name='supporting_document',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='file',
        ),
        migrations.AddField(
            model_name='bankfile',
            name='file_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bankfile',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankfile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankfile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='document_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='document_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='document_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='document_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='file_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
