# Generated by Django 6.0.1 on 2026-02-05 23:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_bank_salaryband_salarylevel_staffcategory_bankbranch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollCalendar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], db_index=True)),
                ('name', models.CharField(help_text='e.g., "January 2025"', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Calendar',
                'verbose_name_plural': 'Payroll Calendar',
                'db_table': 'payroll_calendar',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='calendar',
            field=models.ForeignKey(blank=True, help_text='Calendar month/year this transaction applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_transactions', to='payroll.payrollcalendar'),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='calendar',
            field=models.ForeignKey(blank=True, help_text='Calendar month/year this period belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_periods', to='payroll.payrollcalendar'),
        ),
    ]
