# Generated by Django 6.0.1 on 2026-02-05 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_payroll_calendar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_advance_period', models.BooleanField(default=False, help_text='Automatically advance to next period when current period is closed')),
                ('default_transaction_status', models.CharField(default='ACTIVE', help_text='Default status for new employee transactions', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_calendar', models.ForeignKey(blank=True, help_text='Currently active payroll calendar month', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_as_active', to='payroll.payrollcalendar')),
                ('active_period', models.ForeignKey(blank=True, help_text='Currently active payroll period for processing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_as_active', to='payroll.payrollperiod')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Settings',
                'verbose_name_plural': 'Payroll Settings',
                'db_table': 'payroll_settings',
            },
        ),
    ]
