# Generated by Django 6.0.1 on 2026-02-06 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_payroll_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcategory',
            name='salary_band',
            field=models.ForeignKey(blank=True, help_text='Default salary band for this staff category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_categories', to='payroll.salaryband'),
        ),
    ]
