# Generated by Django 6.0.1 on 2026-02-06 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_allow_null_grade'),
        ('organization', '0004_allow_null_position_grade'),
        ('payroll', '0009_add_salary_structure_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransaction',
            name='job_grade',
            field=models.ForeignKey(blank=True, help_text='Required for GRADE target type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='organization.jobgrade'),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='salary_band',
            field=models.ForeignKey(blank=True, help_text='Required for BAND target type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payroll.salaryband'),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='target_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual Employee'), ('GRADE', 'Job Grade'), ('BAND', 'Salary Band')], db_index=True, default='INDIVIDUAL', help_text='Determines whether this transaction applies to an individual, grade, or band', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeetransaction',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Required for INDIVIDUAL target type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='employeetransaction',
            index=models.Index(fields=['target_type', 'status'], name='employee_tr_target__d9efee_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetransaction',
            index=models.Index(fields=['job_grade', 'status'], name='employee_tr_job_gra_2e062a_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetransaction',
            index=models.Index(fields=['salary_band', 'status'], name='employee_tr_salary__6e54f1_idx'),
        ),
    ]
