# Generated by Django 6.0.1 on 2026-02-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_add_grade_band_to_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollitem',
            name='proration_factor',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Proration factor applied (1.0 = full salary, <1.0 = prorated for mid-period join/exit)', max_digits=5),
        ),
    ]
