# Generated by Django 6.0.1 on 2026-02-08 01:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_add_file_checksum_to_data_update_document'),
        ('payroll', '0011_add_proration_factor_to_payroll_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransaction',
            name='is_current_version',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, help_text='Original transaction this version was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='payroll.employeetransaction'),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='BackpayRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('PROMOTION', 'Promotion'), ('UPGRADE', 'Grade/Level Upgrade'), ('SALARY_REVISION', 'Salary Revision'), ('CORRECTION', 'Payroll Correction'), ('DELAYED_INCREMENT', 'Delayed Increment'), ('BACKDATED_JOINING', 'Backdated Joining Date'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField()),
                ('total_arrears_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_arrears_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_arrears', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('periods_covered', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PREVIEWED', 'Previewed'), ('APPROVED', 'Approved'), ('APPLIED', 'Applied to Payroll'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_to_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backpay_requests', to='payroll.payrollrun')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_backpay_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backpay_requests', to='employees.employee')),
                ('new_salary', models.ForeignKey(blank=True, help_text='Optional reference to the triggering salary change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backpay_as_new', to='payroll.employeesalary')),
                ('old_salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backpay_as_old', to='payroll.employeesalary')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backpay_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackpayDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('applicable_salary', models.ForeignKey(blank=True, help_text='The salary that was effective for this period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backpay_details', to='payroll.employeesalary')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('original_payroll_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backpay_details', to='payroll.payrollitem')),
                ('pay_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backpay_details', to='payroll.paycomponent')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backpay_details', to='payroll.payrollperiod')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('backpay_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payroll.backpayrequest')),
            ],
            options={
                'db_table': 'backpay_details',
                'ordering': ['payroll_period__start_date', 'pay_component__display_order'],
            },
        ),
        migrations.AddField(
            model_name='payrollitemdetail',
            name='backpay_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_item_details', to='payroll.backpayrequest'),
        ),
        migrations.AddIndex(
            model_name='backpayrequest',
            index=models.Index(fields=['employee', 'status'], name='backpay_req_employe_6c883c_idx'),
        ),
        migrations.AddIndex(
            model_name='backpayrequest',
            index=models.Index(fields=['status', '-created_at'], name='backpay_req_status_358680_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='backpaydetail',
            unique_together={('backpay_request', 'payroll_period', 'pay_component')},
        ),
    ]
