# Generated by Django 6.0.1 on 2026-02-08 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_transaction_versioning_and_backpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='backpayrequest',
            name='payroll_period',
            field=models.ForeignKey(blank=True, help_text='Active payroll period when this backpay was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backpay_requests_created', to='payroll.payrollperiod'),
        ),
        migrations.AddField(
            model_name='backpayrequest',
            name='reference_period',
            field=models.ForeignKey(blank=True, help_text='Payroll period whose salary/transaction data to use for new figures', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backpay_requests_referenced', to='payroll.payrollperiod'),
        ),
    ]
