# Generated by Django 6.0.1 on 2026-02-08 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_backpay_period_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='processing_period',
            field=models.ForeignKey(blank=True, help_text='The active payroll period when this salary record was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_changes_during', to='payroll.payrollperiod'),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='processing_period',
            field=models.ForeignKey(blank=True, help_text='The active payroll period when this transaction was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_changes_during', to='payroll.payrollperiod'),
        ),
    ]
