# Generated by Django 6.0.1 on 2026-02-10 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_processing_period_tracking'),
        ('organization', '0004_allow_null_position_grade'),
        ('payroll', '0014_processing_period_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryUpgradeRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('reason', models.CharField(choices=[('PROMOTION', 'Promotion'), ('GRADE_UPGRADE', 'Grade Upgrade'), ('NOTCH_INCREMENT', 'Notch Increment'), ('SALARY_REVISION', 'Salary Revision'), ('OTHER', 'Other')], max_length=20)),
                ('effective_from', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('is_bulk', models.BooleanField(default=False)),
                ('bulk_reference', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salary_upgrades', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_upgrade_requests', to='employees.employee')),
                ('new_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrade_requests', to='organization.jobgrade')),
                ('new_notch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upgrade_requests', to='payroll.salarynotch')),
                ('new_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrade_requests', to='organization.jobposition')),
                ('processing_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_upgrade_requests', to='payroll.payrollperiod')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salary_upgrade_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='salary_upgr_status_f9b55f_idx'), models.Index(fields=['employee', '-created_at'], name='salary_upgr_employe_053ccf_idx'), models.Index(fields=['bulk_reference'], name='salary_upgr_bulk_re_44e098_idx')],
            },
        ),
    ]
