# Generated by Django 6.0.1 on 2026-02-10 20:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_salary_upgrade_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Multiplier for calculated amount (e.g., overtime hours)', max_digits=8),
        ),
    ]
