# Generated by Django 6.0.1 on 2026-02-11 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_add_quantity_to_employee_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryIncrementHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('increment_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('AMOUNT', 'Fixed Amount')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField()),
                ('status', models.CharField(default='APPLIED', max_length=10)),
                ('notches_affected', models.PositiveIntegerField(default=0)),
                ('employees_affected', models.PositiveIntegerField(default=0)),
                ('total_old_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_new_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_increments_applied', to=settings.AUTH_USER_MODEL)),
                ('band', models.ForeignKey(blank=True, help_text='If set, only notches in this band were affected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='increment_history', to='payroll.salaryband')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(blank=True, help_text='If set, only notches in this level were affected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='increment_history', to='payroll.salarylevel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salary_increment_history',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryIncrementDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('notch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increment_details', to='payroll.salarynotch')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('increment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payroll.salaryincrementhistory')),
            ],
            options={
                'db_table': 'salary_increment_details',
                'unique_together': {('increment', 'notch')},
            },
        ),
    ]
