# Generated by Django 6.0.1 on 2026-02-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_add_salary_increment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryupgraderequest',
            name='increment_type',
            field=models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage'), ('AMOUNT', 'Fixed Amount')], help_text='Set when upgrade was created via percentage or amount increment mode.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salaryupgraderequest',
            name='increment_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The percentage or amount value used for the increment.', max_digits=12, null=True),
        ),
    ]
