# Generated by Django 6.0.1 on 2026-02-12 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_erp_schema_enhancements'),
        ('payroll', '0019_adhocpayment_tenant_backpaydetail_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycomponent',
            name='employer_gl_account',
            field=models.ForeignKey(blank=True, help_text='GL account for employer contribution portion (e.g., employer SSNIT)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_pay_components', to='finance.account'),
        ),
        migrations.AddField(
            model_name='paycomponent',
            name='gl_account',
            field=models.ForeignKey(blank=True, help_text='GL account for posting this component (salary expense, tax liability, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_components', to='finance.account'),
        ),
    ]
