# Generated by Django 6.0.1 on 2026-02-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_costcenter_code_alter_department_code_and_more'),
        ('payroll', '0022_payrollvalidation_approval_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='paycomponent',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='removalreasoncategory',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryband',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='staffcategory',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='taxrelief',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='paycomponent',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='payrollcalendar',
            unique_together={('tenant', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='payrollperiod',
            unique_together={('tenant', 'year', 'month', 'is_supplementary')},
        ),
        migrations.AlterUniqueTogether(
            name='removalreasoncategory',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='salaryband',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='salarystructure',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='staffcategory',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='taxrelief',
            unique_together={('tenant', 'code')},
        ),
    ]
