# Generated by Django 6.0.1 on 2026-02-13 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_alter_bank_code_alter_paycomponent_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryincrementhistory',
            name='is_forecast',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='salaryincrementhistory',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryincrementhistory',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_increments_reversed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryincrementhistory',
            name='status',
            field=models.CharField(choices=[('FORECAST', 'Forecast (Test Run)'), ('APPLIED', 'Applied'), ('REVERSED', 'Reversed')], db_index=True, default='APPLIED', max_length=10),
        ),
    ]
