# Generated by Django 6.0.1 on 2026-02-04 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_model', models.CharField(choices=[('employees', 'Employees'), ('leave_balances', 'Leave Balances'), ('transactions', 'Payroll Transactions'), ('departments', 'Departments'), ('positions', 'Job Positions')], db_index=True, max_length=50)),
                ('column_mapping', models.JSONField(default=dict)),
                ('default_values', models.JSONField(default=dict, help_text='Default values for unmapped fields')),
                ('transformation_rules', models.JSONField(default=dict, help_text='Data transformation rules')),
                ('is_public', models.BooleanField(default=False, help_text='Available to all users')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_templates',
                'ordering': ['target_model', 'name'],
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=20)),
                ('target_model', models.CharField(choices=[('employees', 'Employees'), ('leave_balances', 'Leave Balances'), ('transactions', 'Payroll Transactions'), ('departments', 'Departments'), ('positions', 'Job Positions')], db_index=True, max_length=50)),
                ('instructions', models.TextField(blank=True, help_text="User's natural language instructions for mapping", null=True)),
                ('column_mapping', models.JSONField(default=dict, help_text='Maps source columns to target fields')),
                ('mapping_confidence', models.JSONField(default=dict, help_text='Confidence scores for each mapping (0-1)')),
                ('headers', models.JSONField(default=list, help_text='Column headers from source file')),
                ('sample_data', models.JSONField(default=list, help_text='Sample rows for preview (first 5-10 rows)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARSING', 'Parsing File'), ('MAPPING', 'Column Mapping'), ('VALIDATING', 'Validating Data'), ('PREVIEW', 'Ready for Preview'), ('IMPORTING', 'Importing Data'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('skip_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(default=list, help_text='List of error details by row')),
                ('validation_errors', models.JSONField(default=list, help_text='Validation errors from preview')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='imports.importtemplate')),
            ],
            options={
                'db_table': 'import_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=10)),
                ('message', models.TextField()),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('original_value', models.TextField(blank=True, null=True)),
                ('processed_value', models.TextField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='imports.importjob')),
            ],
            options={
                'db_table': 'import_logs',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['import_job', 'level'], name='import_logs_import__bbf658_idx'), models.Index(fields=['import_job', 'row_number'], name='import_logs_import__7eacd4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status', 'created_at'], name='import_jobs_status_aedc42_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['target_model', 'status'], name='import_jobs_target__f8c2dd_idx'),
        ),
    ]
