# Generated by Django 6.0.1 on 2026-02-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_alter_importjob_target_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='target_model',
            field=models.CharField(choices=[('employees', 'Employees'), ('leave_balances', 'Leave Balances'), ('transactions', 'Payroll Transactions'), ('departments', 'Departments'), ('positions', 'Job Positions'), ('grades', 'Job Grades'), ('job_categories', 'Job Categories'), ('divisions', 'Divisions'), ('directorates', 'Directorates'), ('work_locations', 'Work Locations'), ('banks', 'Banks'), ('bank_branches', 'Bank Branches'), ('staff_categories', 'Staff Categories'), ('salary_bands', 'Salary Bands'), ('salary_levels', 'Salary Levels'), ('salary_notches', 'Salary Notches'), ('pay_components', 'Pay Components'), ('leave_types', 'Leave Types'), ('holidays', 'Holidays'), ('bank_accounts', 'Bank Accounts')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='importtemplate',
            name='target_model',
            field=models.CharField(choices=[('employees', 'Employees'), ('leave_balances', 'Leave Balances'), ('transactions', 'Payroll Transactions'), ('departments', 'Departments'), ('positions', 'Job Positions'), ('grades', 'Job Grades'), ('job_categories', 'Job Categories'), ('divisions', 'Divisions'), ('directorates', 'Directorates'), ('work_locations', 'Work Locations'), ('banks', 'Banks'), ('bank_branches', 'Bank Branches'), ('staff_categories', 'Staff Categories'), ('salary_bands', 'Salary Bands'), ('salary_levels', 'Salary Levels'), ('salary_notches', 'Salary Notches'), ('pay_components', 'Pay Components'), ('leave_types', 'Leave Types'), ('holidays', 'Holidays'), ('bank_accounts', 'Bank Accounts')], db_index=True, max_length=50),
        ),
    ]
