# Generated by Django 6.0.1 on 2026-02-05 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_alter_importjob_target_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='detected_model',
            field=models.CharField(blank=True, help_text='AI-detected target model', max_length=50),
        ),
        migrations.AddField(
            model_name='importjob',
            name='detection_confidence',
            field=models.FloatField(default=0.0, help_text='AI confidence in the detected model (0-1)'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='processing_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which this job should be processed within the batch'),
        ),
        migrations.CreateModel(
            name='MultiFileImportBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Optional name for this batch import', max_length=200)),
                ('instructions', models.TextField(blank=True, help_text="User's natural language instructions for the batch", null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANALYZING', 'Analyzing Files'), ('READY', 'Ready for Review'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partially Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('analysis_results', models.JSONField(default=dict, help_text='AI analysis results for each file')),
                ('processing_order', models.JSONField(default=list, help_text='Determined order for processing files')),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('files_completed', models.PositiveIntegerField(default=0)),
                ('files_failed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_create_dependencies', models.BooleanField(default=True, help_text='Automatically create missing setup records (e.g., banks, departments)')),
                ('update_existing', models.BooleanField(default=True, help_text='Update existing records if found')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'multi_file_import_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='importjob',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='imports.multifileimportbatch'),
        ),
    ]
