# Generated by Django 6.0.1 on 2026-02-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_dataset_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='celery_task_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Celery task ID for background processing',
                max_length=255,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='multifileimportbatch',
            name='celery_task_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Celery task ID for background processing',
                max_length=255,
                null=True
            ),
        ),
    ]
