# Generated by Django 6.0.1 on 2026-02-06 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_directorate_department_directorate_division_and_more'),
        ('payroll', '0009_add_salary_structure_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobgrade',
            name='salary_band',
            field=models.ForeignKey(blank=True, help_text='Salary band applicable to this job grade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_grades', to='payroll.salaryband'),
        ),
        migrations.AddField(
            model_name='jobgrade',
            name='salary_level',
            field=models.ForeignKey(blank=True, help_text='Default salary level for this job grade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_grades', to='payroll.salarylevel'),
        ),
    ]
