# Generated by Django 6.0.1 on 2026-02-12 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_allow_null_position_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('logo_data', models.BinaryField(blank=True, null=True)),
                ('logo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_color', models.CharField(default='#1a365d', max_length=7)),
                ('country', models.CharField(blank=True, max_length=3)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('financial_year_start_month', models.PositiveSmallIntegerField(default=1)),
                ('leave_year_start_month', models.PositiveSmallIntegerField(default=1)),
                ('payroll_processing_day', models.PositiveSmallIntegerField(default=25)),
                ('email_domain', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('from_email', models.EmailField(default='noreply@example.com', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_plan', models.CharField(choices=[('FREE', 'Free'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], default='STANDARD', max_length=20)),
                ('max_employees', models.PositiveIntegerField(default=500)),
                ('max_users', models.PositiveIntegerField(default=100)),
                ('trial_expires_at', models.DateTimeField(blank=True, null=True)),
                ('modules_enabled', models.JSONField(default=list)),
                ('setup_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='costcenter',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='directorate',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='division',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='jobgrade',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organization.organization'),
        ),
    ]
