# Generated by Django 6.0.1 on 2026-02-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_costcenter_tenant_department_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='division',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='code',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jobgrade',
            name='code',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='worklocation',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='directorate',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='jobcategory',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='jobgrade',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='jobposition',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationunit',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='worklocation',
            unique_together={('tenant', 'code')},
        ),
    ]
