# Generated by Django 6.0.1 on 2026-02-13 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_costcenter_code_alter_department_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('license_type', models.CharField(choices=[('TRIAL', 'Trial'), ('FREE', 'Free'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], default='STANDARD', max_length=20)),
                ('max_users', models.PositiveIntegerField(default=10)),
                ('max_employees', models.PositiveIntegerField(default=50)),
                ('modules_allowed', models.JSONField(blank=True, default=list, help_text='List of module names enabled by this license')),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_licenses', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='organization.organization')),
            ],
            options={
                'db_table': 'licenses',
                'ordering': ['-valid_from'],
            },
        ),
    ]
